### PR TITLE
[chore] upgrade to Erlang/OTP 25

### PR DESCRIPTION
**Pull request by claudinemcg**
linked to [STE-1811 Upgrade to Erlang/OTP 25](https://linear.app/steadyhq/issue/STE-1811/upgrade-erlangotp-to-25-in-main-app)

### CODE REVIEW

**Comment by angelikatyborska** [comment]
This project has CircleCI set up differently than main app and requires more changes when language versions get updated. In main app, we use a generic Docker image in CircleCi and install the right language versions via asdf when the CI job runs. In this project, we use a Docker image that comes with Erlang and Elixir preinstalled.

In the CircleCI config file, you can find this line:
```
    docker:
      - image: cimg/elixir:1.13.3
```

The part after `:` is called a tag. Here you will find a list of all tags available for this Docker image: https://hub.docker.com/r/cimg/elixir/tags

We need to find one that has Elixir 1.13.3 and OTP 25.0.3 (without "browsers" or "node"). I think it doesn't exist there so we might be forced to use an image with Elixir 1.13.4 instead.

**Comment by angelikatyborska** [comment]
Ah, actually, main app is on Elixir 1.13.4-otp-25, so we can also change 1.13.3 to 1.13.4 in this project.

**Comment by claudinemcg** [comment]
@angelika do I need to change erlang in CircleCI config file, too?

**Comment by angelikatyborska** [comment]
@claudinemcg In this project, you update Erlang on CircleCI indirectly based on which `cmig/elixir` tag you're using. Technically it would have been better to use the tag `cimg/elixir:1.13.4-erlang-25.0.3` instead of `cimg/elixir:1.13.4` so that it's immediately clear which Erlang version is in there, but practically those are exactly the same Docker images, both have Erlang 25.0.3. I know that because their digests are identical:
Screenshot 2022-08-25 at 06 24 09
Screenshot 2022-08-25 at 06 24 02

**Review by angelikatyborska — APPROVED** [review]

**Comment by claudinemcg** [comment]
@angelikatyborska I wasn't sure which of those to use, I went with just elixir because the cimg in the file only had elixir. I never noticed that those two codes are the same.

**Pull request merged**
